volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    env_file: .env
    image: postgres:13
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: borpa/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: borpa/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: borpa/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static/
      - media_volume:/media/
    depends_on:
      - backend
